version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: banco-postgres
    environment:
      POSTGRES_DB: first_decision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - app-net

  springboot:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/first_decision
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge